name: myenv
channels:
  - defaults
  - pytorch
  - huggingface
dependencies:
  - python=3.10
  - pip
  - pip:
    - accelerate==0.32.1
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - async-timeout==4.0.3
    - attrs==23.2.0
    - certifi==2024.7.4
    - charset-normalizer==3.3.2
    - click==8.1.7
    - datasets==2.20.0
    - dill==0.3.8
    - docker-pycreds==0.4.0
    - filelock==3.15.4
    - frozenlist==1.4.1
    - fsspec==2024.5.0
    - gitdb==4.0.11
    - GitPython==3.1.43
    - huggingface-hub==0.24.0
    - idna==3.7
    - importlib_metadata==8.0.0
    - Jinja2==3.1.4
    - MarkupSafe==2.1.5
    - mpmath==1.3.0
    - multidict==6.0.5
    - multiprocess==0.70.16
    - networkx==3.3
    - numpy==1.26.4
    - packaging==24.1
    - pandas==2.2.2
    - pillow==10.4.0
    - platformdirs==4.2.2
    - protobuf==5.27.2
    - psutil==6.0.0
    - pyarrow==17.0.0
    - pyarrow-hotfix==0.6
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - PyYAML==6.0.1
    - regex==2024.5.15
    - requests==2.32.3
    - safetensors==0.4.3
    - sentencepiece==0.2.0
    - sentry-sdk==2.10.0
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - sympy==1.13.1
    - tokenizers==0.19.1
    - torch==2.3.1
    - torchvision==0.18.1
    - tqdm==4.66.4
    - transformers==4.42.4
    - triton==2.3.1
    - typing_extensions==4.12.2
    - tzdata==2024.1
    - urllib3==2.2.2
    - wandb==0.17.5
    - xxhash==3.4.1
    - yarl==1.9.4
    - zipp==3.19.2
    - opencv-python==4.7.0.72 
    - git+https://github.com/huggingface/diffusers.git@1a8b3c2ee86c09d0d3e066f7e9ea2ab69e8e78fa#egg=diffusers